# Site info
title:                "My awesome blog"
lang:                 "en"
description:          "About the woodlands I will go"
google_analytics:     "UA-XXXXXXX-X"
  
# Author info 
author_name:          "Jimmy Forester"
author_email:         "jimmy@example.com"
author_about:         "/about"
author_web:           "example.com"
  
# Site settings 
baseurl:              "/forest-time-jekyll"
url:                  "http://localhost:4000/"
permalink:            "/:title"
paginate:             4
paginate_path:        "/page:num"
  
# Custom parameters 
brandingFolder:       "/assets/icons"
oldPostNoticeBefore:  2018-11-15 08:00:00 +0200 # display a notice for posts older than this date
minimalistHome:       false # experimental - hides post date and excerpt, centers title on homepage

# Other Params
include:            [ "Gemfile" ]
exclude:            [ "LICENSE.md", "README.md", "test-gem", "scripts", "vendor", "forest-time-jekyll.gemspec" ]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - tzinfo

feed:
  path: feed.xml