# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Learned...
email: gaboratorium@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gabor Pinter's Devblog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gaborpinter.net" # the base hostname & protocol for your site
twitter_username: gaboratorium
github_username:  gaboratorium

# Build settings
markdown: kramdown
