# Site info
title:                "My awesome blog"
lang:                 "en"
description:          "About the woodlands I will go"
google_analytics:     "UA-XXXXXXX-X"
  
# Author info 
author:               "Jimmy Forester"
author_email:         "jimmy@example.com"
author_about:         "/about"
author_contact:       "/contact"
  
# Site settings 
baseurl:              "/forest-time-jekyll"
url:                  "https://claudiuconstantin.github.io"
permalink:            "/:title"
paginate:             4
paginate_path:        "/page:num"
showComments:         true

# Mailchimp newsletter
mailchimp:
  url:                "https://your-url-here.us6.list-manage.com/subscribe/post?u=your-u-here&amp;id=your-id-here"
  inputName:          "your-input-name-here"

# Custom parameters 
brandingFolder:       "/assets/icons"
oldPostNoticeBefore:  2018-11-15 08:00:00 +0200 # display a notice for posts older than this date
timezone:             "Europe/Bucharest"

# TODO: create a separate home layour for this
# minimalistHome:       false # experimental - hides post date and excerpt, centers title on homepage

# Other Params
include:            [ "Gemfile" ]
exclude:            [ "LICENSE.md", "README.md", "test-gem", "scripts", "vendor", "forest-time-jekyll.gemspec" ]