
title: "Your awesome site"
lang: "en"
email: john.doe@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author info
author_name:      "John Doer"
author_email:     john.doe@example.com
author_about:     /about-john
author_web:       example.com

# Site settings
baseurl:          "/test"
paginate:         3
paginate_path:    "/page:num"
brandingFolder:   "/assets/icons"

# Build settings
markdown: kramdown
theme: forest-time-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
