
title: "Your awesome site"
lang: "en"
email: john.doe@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author info
author:               "John Doer"
author_email:         "john.doe@example.com"
author_about:         "/about-john"
author_web:           "example.com"
    
# Site settings   
baseurl:              "/test"
paginate:             3
paginate_path:        "/page:num"
brandingFolder:       "/assets/icons"
oldPostNoticeBefore:  2018-12-02 08:00:00 +0200 # display a notice for posts older than this date

# Build settings
markdown: kramdown
theme: forest-time-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
